[package]
name = "osbuild-mod"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "stage-test"
path = "src/bin/stage/test/main.rs"

[dependencies]
libosbuild = { path = "../libosbuild" }
